### ISSUE TITLE
Compiler Should Use Exception-Safety Flag

### ISSUE THREAD

**Issue by Adlai-Holler** [pinterest/PINCache#105]
PINDiskCache.m should be compiled with `f-objc-arc-exceptions` so that ARC is made exception safe.

In the podspec, you can break those files out into a subspec and make that subspec part of the default spec:

```
  s.subspec 'exception-safe' do |sp|
    sp.source_files = 'PINDiskCache.m'
    sp.compiler_flags = '-f-objc-arc-exceptions`
  end
```

**Comment by garrettmoon** [comment]
Awesome catch!
