### ISSUE TITLE
warning of version 2.3 

### ISSUE THREAD

**Issue by crespoxiao** [pinterest/PINCache#109]
hi, please check the image.

<img width="1130" alt="2016-09-02 11 53 19" src="https://cloud.githubusercontent.com/assets/1168793/18192137/0130cfba-7104-11e6-8d6a-61f78d9e87b5.png">

**Comment by garrettmoon** [comment]
I'm out of the country so won't be able to address this for a few weeks, but I will try and merge a pull request if you put one up!

**Comment by garrettmoon** [comment]
I just ran the analyzer on master and this doesn't appear. Am I missing something?
