### ISSUE TITLE
crash on version 2.2.2 

### ISSUE THREAD

**Issue by crespoxiao** [pinterest/PINCache#110]
hi , there is a low probability(happened once in 30 days) crash when use API objectforkey: ,please check the image below. Is version 2.3 fixed this crash ? 

<img width="506" alt="2016-09-02 11 57 26" src="https://cloud.githubusercontent.com/assets/1168793/18192183/9146f19c-7104-11e6-8ec1-625a6e08d47e.png">
 
<img width="590" alt="2016-09-02 12 01 19" src="https://cloud.githubusercontent.com/assets/1168793/18192240/02816bee-7105-11e6-90e1-9d91d73e3b69.png">
<img width="734" alt="2016-09-02 12 01 08" src="https://cloud.githubusercontent.com/assets/1168793/18192244/05753f92-7105-11e6-8e19-945a8bcd7d07.png">

**Comment by garrettmoon** [comment]
The stack trace doesn't indicate PINCache. I'm not sure I understand. I can reopen the issue if you provide more details.

**Comment by crespoxiao** [comment]
hi @garrettmoon  , this crash only affected one user. maybe the phone has some problem or some special condition lead this crash.you can check the images below, hopely you can find something.please let me know when you fix it.
<img width="1191" alt="2016-09-06 10 26 42" src="https://cloud.githubusercontent.com/assets/1168793/18297741/b2876c30-74e5-11e6-94eb-e1812e565db5.png">
<img width="1165" alt="2016-09-06 10 26 52" src="https://cloud.githubusercontent.com/assets/1168793/18297742/b4b1714a-74e5-11e6-9b39-3e8943b8115f.png">

**Comment by garrettmoon** [comment]
I don't have any solid leads as to why this would occur :(

Very strange that it's only affecting one user…

**Comment by appleguy** [comment]
This is a very unusual exception code - EXC_BAD_INSTRUCTION.  Are you by chance using BitCode?  This could be a corruption of the binary / app on the user's phone (e.g. due to a faulty area of flash memory or something else).  This theory could be supported by the fact that there are 12 crashes (consistent), but from the same user.
