### ISSUE TITLE
Invalid task ids used for expiration handlers.

### ISSUE THREAD

**Issue by jaredsinclair** [pinterest/PINCache#13]
The macro for beginning a background task looks like this:

```
UIBackgroundTaskIdentifier taskID = UIBackgroundTaskInvalid;
taskID = [[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:^{
    [[UIApplication sharedApplication] endBackgroundTask:taskID]; 
}];
```

`UIBackgroundTaskIdentifier` is a value type, so when the block is created it captures `taskID` when it equals `UIBackgroundTaskInvalid`. It never captures the actual task identifier, so if the expiration handler pops the actual task isn't properly cancelled.

**Comment by garrettmoon** [comment]
Yup.

**Comment by garrettmoon** [comment]
@jaredsinclair Let me know what you think of #14

**Comment by jaredsinclair** [comment]
# lg™
