### ISSUE TITLE
Hey, Why use NSMutableOrderSet and NSMapTable in PINCacheOperationQueue and group?

### ISSUE THREAD

**Issue by WildDylan** [pinterest/PINCache#133]
Hey, Why use NSMutableOrderSet and NSMapTable in PINCacheOperationQueue and group?

**Comment by garrettmoon** [comment]
@WildDylan Can you elaborate? What data structures do you think would be more appropriate?

**Comment by WildDylan** [comment]
@garrettmoon haha, i just want know why use it ...
