### ISSUE TITLE
+emptyTrash operation can be optimized by deleting directory as a whole (rather than enumerating files).

### ISSUE THREAD

**Issue by appleguy** [pinterest/PINCache#136]
I tried this locally and it's a great win - but a little bit of extra work is needed to make it safe.  We simply need to ensure another directory is created to replace it, before any other file is moved there.

A great implementation would create the trash in a random place, and then when the trash is emptied, delete that place + have the sharedTrashURL's cached URL be cleared.  Then the next time sharedTrashURL is called, we would see there's no cached global URL, and create a new UUID-named trash folder.  This would eliminate any checks for whether the directory exists too.

This trace was taken on an iPod 5G, after suspending the app, measuring _only the app resume_ operation - with no user interaction.

<img width="847" alt="screen shot 2016-10-28 at 3 21 06 pm" src="https://cloud.githubusercontent.com/assets/565251/19824190/3c659242-9d22-11e6-9322-c7f46f9700c8.png">

**Comment by nguyenhuy** [comment]
Optimization merged!
