### ISSUE TITLE
Reduce frequency / cost of calls to +emptyTrash and -trimToByteSize: (tolerance % for cleanup)

### ISSUE THREAD

**Issue by appleguy** [pinterest/PINCache#137]
Currently we spend a large total resource on calls to these methods.

The example here is from resuming the app on iPod 5G _without_ any user interaction.  Note that when this happens, we re-render a significant number of views that expand their working ranges, so accesses to the cache are common; however, we shouldn't be downloading any new images.

The file read operations would be expected to be the most expensive part of this (in addition to the decodes).  However the total cache access / file read costs are very modest in comparison to the cleanup operations, which are a large multiple of the read costs!

Adding the two type of dispatch stacks, there's about 2,000ms of work in total.  Only 360ms are file reads!

<img width="850" alt="screen shot 2016-10-28 at 4 29 55 pm" src="https://cloud.githubusercontent.com/assets/565251/19825318/57953554-9d2c-11e6-85c9-51c5dd2ed401.png">
<img width="857" alt="screen shot 2016-10-28 at 4 31 10 pm" src="https://cloud.githubusercontent.com/assets/565251/19825284/f9dedcb2-9d2b-11e6-9728-020a2b8d2e91.png">

**Comment by nguyenhuy** [comment]
Fixed!
