### ISSUE TITLE
[Performance] -initializeDiskProperties can take >1.5s on startup.

### ISSUE THREAD

**Issue by appleguy** [pinterest/PINCache#144]
cc @garrettmoon @nguyenhuy We need to optimize this — the duration is long enough that it impacts the time to use the cache on app startup, which can block image display even though it's off the main thread.

We should spend an hour looking for a simple way to do this — maybe a directory listing query that collects less information about each file, or maintaining a very simple manifest file of current files.

<img width="1396" alt="screen shot 2016-11-15 at 2 05 09 pm" src="https://cloud.githubusercontent.com/assets/565251/20326350/3901bc7e-ab3d-11e6-8870-583154b46e3e.png">

**Comment by garrettmoon** [comment]
If we go with the manifest idea, we'll need to consider how crashes / kills will affect it.

**Comment by appleguy** [comment]
Yes definitely, some complications with the manifest.  One option would be to occasionally create a new cache directory to put newer files in, and entirely delete the previous one.

**Comment by garrettmoon** [comment]
This has been addressed in https://github.com/pinterest/PINCache/pull/203

**Comment by garrettmoon** [comment]
Going to close for now, if it still seems to be an issue in profiling we'll reopen.
