### ISSUE TITLE
Can't build with the newest project.

### ISSUE THREAD

**Issue by xueminlee** [pinterest/PINCache#172]
The issue is: /Users/xueminli/Developement/Zhubajie/work.place/PINCache/Source/PINCache.m:7:9: 'PINOperation/PINOperation.h' file not found.
Could you please help me to find the issue?

Thanks,
Andy

**Comment by xueminlee** [comment]
Why use PINOperation in PINCache?

**Comment by maicki** [comment]
@xueminlee We are using `PINOperation` within `PINCache` as it's a better abstraction on top of GCD  . How do you pull `PINCache` into your project? Using Cocoapods or Carthage should work without any problems.

**Comment by garrettmoon** [comment]
If you use Carthage, you *will* have to link and copy the PINOperation framework into your application. The project itself should build fine on master…

**Comment by garrettmoon** [comment]
@xueminlee since there has been no reply in a while, I'm going to close this, however please reply back if you are still having issues.
