### ISSUE TITLE
Can't build OS X framework.

### ISSUE THREAD

**Issue by lexrus** [pinterest/PINCache#18]
Failed to build the framework when targeting OS X.
<img width="1039" alt="screen shot 2015-07-31 at 10 32 35 pm" src="https://cloud.githubusercontent.com/assets/219689/9009502/329be57c-37d4-11e5-9bd9-3cb9704ddf84.png">

**Comment by garrettmoon** [comment]
Ouch, thanks for catching this!

**Comment by garrettmoon** [comment]
I'll put up a PR to fix today, and add in os x to our Travis CI builds.

**Comment by garrettmoon** [comment]
Fix is here: #19

**Comment by lexrus** [comment]
Okay, it compiled without problems. Thank you.
