### ISSUE TITLE
Can I store data to except NSCachesDirectory?

### ISSUE THREAD

**Issue by muukii** [pinterest/PINCache#180]

**Comment by appleguy** [comment]
Could you clarify? The title isn't quite understandable, so please describe your use case / what behavior you'd like to have.

Also check out the API & implementation of PINDiskCache to see if it can give you any clues; it's possible you need to suggest a new API be added here, but if you can make a comment about what such an API would do, it will help us understand if it's a feature that needs to be added to the framework or that you can handle at the app layer.  Note I think it is possible to create multiple PINDiskCaches manually (unsure though)

**Comment by muukii** [comment]
@appleguy 

Thank you.
I'll try to save it in a location other than the Cache directory.
