### ISSUE TITLE
Turn off ARC exceptions

### ISSUE THREAD

**Issue by michaeleiselsc** [pinterest/PINCache#184]
-fobjc-arc-exceptions is turned on for PINDiskCache, which, according to the docs, will cause that file to be significantly slower and larger in size. perhaps the exceptions could be replaced with assertion fails, or just allow the memory to leak

**Comment by garrettmoon** [comment]
@michaeleiselsc I would love to know the actual costs to speed and app size before making this tradeoff…

**Comment by michaeleiselsc** [comment]
hard to say, but perhaps it'd be worth profiling

**Comment by michaeleiselsc** [comment]
from https://clang.llvm.org/docs/AutomaticReferenceCounting.html:
"The standard Cocoa convention is that exceptions signal programmer error and are not intended to be recovered from. Making code exceptions-safe by default would impose severe runtime and code size penalties on code that typically does not actually care about exceptions safety. Therefore, ARC-generated code leaks by default on exceptions, which is just fine if the process is going to be immediately terminated anyway. Programs which do care about recovering from exceptions should enable the option."

**Comment by michaeleiselsc** [comment]
it's also, iirc, turned off by default for new projects

**Comment by garrettmoon** [comment]
@michaeleiselsc the way I read that says we *should* have the recovered exceptions. We don't terminate the program on exception *and* the file API explicitly says it throws exceptions on errors. And in practice it does it a lot when setting dates :(

**Comment by michaeleisel** [comment]
interesting, i wonder if we could isolate the places where we *need* exception safe code, and put those into a separate file

**Comment by garrettmoon** [comment]
@michaeleiselsc further than the disk cache? They're only enabled for the disk cache currently.

**Comment by garrettmoon** [comment]
By the way, I also agree that it's worth profiling before we make this decision. Would love it if someone would post the difference. To be frank, this hasn't come up in any traces at Pinterest so I'm unlikely to take the time to investigate.

**Comment by michaeleisel** [comment]
It won't come up in any traces because it affects everything a little bit. It's not adding/removing method calls, but it's allowing the compiler to make further optimizations, allocate less memory, etc.

**Comment by michaeleisel** [comment]
although you can't be too sure, if the pin disk cache's time is mostly spent in frameworks that it calls into, then yeah you won't see much gain

**Comment by garrettmoon** [comment]
@michaeleisel if it doesn't show up in the profiler, it doesn't seem worth it to me? And yeah, PINDiskCache is bound by I/O primarily.

**Comment by michaeleisel** [comment]
makes sense

**Comment by garrettmoon** [comment]
Cool, I'm going to close this out for now, happy to continue discussion if someone would like to post some profiling data.
