### ISSUE TITLE
PINCache crashes when low disk memory.

### ISSUE THREAD

**Issue by MaxAdamyan** [pinterest/PINCache#187]
Hi. I'm using PINCache to cache some images using this methods:
`PINCache.shared().setObject(image, forKey: "key")`
`PINCache.shared().object(forKey: "key")`
There is problem when user has very low disk memory, and when PINChache tries to cache an image app crashes. I'm using Crashlytis for bug reporting and I'm pretty sure that this is the case. What can I do to fix this crashes?? 
Thanks.

**Comment by garrettmoon** [comment]
@MaxAdamyan sorry for the delayed reply.

There's sadly not much you can do except possibly limit PINCache's size a bit more. PINCache relies on the system to notify it that low memory has occurred, however iOS does not always deliver it in time before it kills the app :(
