### ISSUE TITLE
Documentations warning

### ISSUE THREAD

**Issue by MarceloJoseML** [pinterest/PINCache#189]
take a look in the following method documentation:
/**
 This method enables using literals on the receiving object, such as `cache[@"key"] = object;`.
 
 @param object An object to be assigned for the key.
 @param key A key to associate with the object. This string will be copied.
 */
- (void)setObject:(id)obj forKeyedSubscript:(NSString *)key;

Replace object for obj to avoid warnings

**Comment by maicki** [comment]
@MarceloJoseML Hey, it seems like this is already fixed on master. Please reopen if not. Thanks!
