### ISSUE TITLE
Cocoa error -1

### ISSUE THREAD

**Issue by MattRidge** [pinterest/PINCache#191]
I am getting this error on iOS 10.3.3 using Pinterest version 6.27

**Comment by garrettmoon** [comment]
@MattRidge This isn't really an actionable report. Can you give more info?

**Comment by MattRidge** [comment]
On my IPhone, Whenever I attempt to download an image to my photo library is when I get this error. That's all the information is ever given to me is a Coco error -1

**Comment by garrettmoon** [comment]
@MattRidge Just so we're clear, this is an error that you get when you use the Pinterest app and has nothing to do with PINCache?

**Comment by MattRidge** [comment]
That is correct. I went to file a bug via the app and I was sent here.

**Comment by garrettmoon** [comment]
@MattRidge That's odd, this is definitely not the right place to file a Pinterest app bug. Can you let me know how you were sent here so I can figure out how to make sure bug reports get routed correctly in the future?

**Comment by MattRidge** [comment]
I originally tried doing a google search for the error after sending a request via Pintrest to see if there was a known bug, etc.  Then I found someone saying that it was a known issue and to post here.  That was a while back so I'm not sure I have the pages anymore...

**Comment by garrettmoon** [comment]
I see, yeah, for future reference bug reports should go here: https://help.pinterest.com/en/login-request
