### ISSUE TITLE
Some links in Readme file are broken

### ISSUE THREAD

**Issue by oferRounds** [pinterest/PINCache#193]
These are: `PINCache`, `PINMemoryCache` and `PINDiskCache` links.

Also, in the sentence: 

> Both `PINMemoryCache` and PINDiskCache...

PINDiskCache does not use the code formatting.

**Comment by oferRounds** [comment]
Cool!

**Comment by garrettmoon** [comment]
Thanks for reporting @oferRounds !

**Comment by oferRounds** [comment]
👍👍
