### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by zkrige** [pinterest/PINCache#208]
Please update cocoapods with the latest version

**Comment by garrettmoon** [comment]
@zkrige the latest released version is on cocoa pods, we'll get to a new release soon!

**Comment by garrettmoon** [comment]
Also as an FYI, you can always point to a specific commit with cocoa pods or just the master branch.

**Comment by zkrige** [comment]
Thanks! 

I noticed some XCode  compiler warnings, and wanted to submit a PR, but the latest code in your repo has fixed the warnings already

I am aware that you can point to the git repo, but I prefer to run everything through standard cocoapods releases.

I'll keep an eye out for the next release.

keep up the amazing work
