### ISSUE TITLE
Change Cache Location under Library OR protect it from being Deleted

### ISSUE THREAD

**Issue by mikeRozen** [pinterest/PINCache#215]
Hi,
I think that current issue is more related to feature.
I noticed that Pincache saves its cache under _Library/Caches/com.pint......._
According to apple documentation this folder will not be preserved during updates and may be deleted on low memory cases (obviously won't be backed up)

[storing private data](https://developer.apple.com/library/content/qa/qa1699/_index.html)
   [file system](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1)

From some tests that I made _Libray/Caches/com.pint..._ does sometimes survive the update process BUT it still can be deleted on certain circumstances.
After some user complaints I am more than sure that this cache is sometimes get deleted.....
1.Is it possible to save my cache in Library directory (according to apple that folder will always be backed up and never will be deleted) 
2.In case of NO for (1). How can I protect my cache from being deleted and be backed up?

Thanks.

**Comment by tanranran** [comment]
+1

**Comment by garrettmoon** [comment]
You can set where you want the disk cache to live when you initialize it: `initWithName:name:rootPath:serializer:deserializer:`

Just specify a different rootPath and that's where the cache will be stored! You'll also need to specify a name. You can pass nil for serializer and deserializer.
