### ISSUE TITLE
Unable to submit app

### ISSUE THREAD

**Issue by vishal2647** [pinterest/PINCache#219]
Guys,
I am unable to submit my app on your website: https://developers.pinterest.com/apps/
I have already authorized my app and when i am trying to submit the app for review process, i am not able to submit it and i am getting “502 Bad Gateway” response and error message is: The MySQL server is running with the — read-only option so it cannot execute this statement.
This is not expected from reputed service like Pinterest. Please fix it as it is hampering our Business.

**Comment by garrettmoon** [comment]
@vishal2647 This isn't the proper place for this feedback.
