### ISSUE TITLE
Cannot initialize with a TTL memory cache

### ISSUE THREAD

**Issue by wiseoldduck** [pinterest/PINCache#226]
`- (instancetype)initWithName:(nonnull NSString *)name
                    rootPath:(nonnull NSString *)rootPath
                  serializer:(nullable PINDiskCacheSerializerBlock)serializer
                deserializer:(nullable PINDiskCacheDeserializerBlock)deserializer
                  keyEncoder:(nullable PINDiskCacheKeyEncoderBlock)keyEncoder
                  keyDecoder:(nullable PINDiskCacheKeyDecoderBlock)keyDecoder
                    ttlCache:(BOOL)ttlCache NS_DESIGNATED_INITIALIZER;`

passing `ttlCache:YES` here only enables ttlCache for the disk cache, the memory cache is still set up as a non-ttl cache. 

This can be corrected after the fact with PINMemoryCache: `- (void)setTtlCache:(BOOL)ttlCache DEPRECATED_MSG_ATTRIBUTE("ttlCache is no longer a settable property and must now be set via initializer.");` but, this is unintuitive, and as you can see this method is marked as deprecated.

**Comment by internalG** [comment]
Yes, it also happens in sharedCache. The TTL support in latest code is confusing.

**Comment by mc7h** [comment]
I was experiencing some strange behaviour calling the deprecated `setTtlCache`. My disk cache was being deleted up instantiation of the manager.

**Comment by mc7h** [comment]
Agreed, it's confusing - I ran into issues once I adopted it - my previous custom cache started deleting the disk cache upon instantiation of the Manager.
Also, shouldn't there be away to turn on TTL for the cache of the default Manager.
