### ISSUE TITLE
Why can't the picture be cached to disk?

### ISSUE THREAD

**Issue by Leon0206** [pinterest/PINCache#229]
UIImage *image = [UIImage imageNamed:@"launch.jpg"];
    [[PINCache sharedCache]setObject:image forKey:@"image_key"];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(10 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [[PINCache sharedCache]objectForKey:@"image_key" block:^(PINCache * _Nonnull cache, NSString * _Nonnull key, id  _Nullable object) {
            NSLog(@"------>%@",object); //print the null
        }];
    });
Now when a MemoryWarningNotification event arrive，i can't get the object like the SDWebImage? is that a bug or not supported?

**Comment by appleguy** [comment]
Suggest you use PINRemoteImage, which is designed to drive PINCache for
this use case.

Have you set some breakpoints in PINDiskCache to make sure it is being
created and configured correctly?

**Comment by Leon0206** [comment]
thank u for your reply, I've tried the following way:
   UIImage *image = [UIImage imageNamed:@"launch.jpg"];
    [[PINDiskCache sharedCache]setObject:image forKey:@"image_disk_key"];
    [[PINDiskCache sharedCache]objectForKey:@"image_disk_key" block:^(PINDiskCache * _Nonnull cache, NSString * _Nonnull key, id<NSCoding>  _Nullable object, NSURL * _Nonnull fileURL) {
        NSLog(@"------>%@",object); //null
  }];
and it is always nil. After I debug the problem, I found that the cache files create successfully and read it fail. But I when i try store the "NSData" instead of the "UIImage" like the SDWebImage, It seems to be successful.

**Comment by garrettmoon** [comment]
@Leon0206 PINDiskCache only supports caching objects which support the NSCoding protocol. UIImage doesn't support this (but you could probably add support).

Hope this helps!

**Comment by garrettmoon** [comment]
As @appleguy said though, PINRemoteImage will handle this for you and supports local file paths.
