### ISSUE TITLE
How to cache pure html in file?

### ISSUE THREAD

**Issue by internalG** [pinterest/PINCache#238]
I want to cache my html strings in file, so that my browser can load that file with value of fileURLForKey. I know there's something about NSCoding and tried, but the cache always saves with keys etc. Is there simple way to cache as a real html file?

**Comment by garrettmoon** [comment]
I'm not sure PINCache is the best way to achieve this. Have you looked into a custom [URLCache](https://developer.apple.com/documentation/foundation/urlcache)?
