### ISSUE TITLE
Disk usage breakdown tool for normal users?

### ISSUE THREAD

**Issue by jaekyeom** [pinterest/PINCache#239]
I'm not an iOS or macOS developer. I just use macOS.

Some time ago, I realized that `~/Library/Caches/com.pinterest.PINDiskCache.PINCacheShared` is taking up a lot of disk space.

Is there any way for normal users to see PINCache's disk usage breakdown by apps? Or maybe an administrative tool that lists all the keys exist?

Thank you.

**Comment by garrettmoon** [comment]
Hmm, no and it's beyond the scope of the library to provide that type of thing for end users – it's up to the software developers creating the apps.

But the keys in general should be the filenames within that directory. Hopefully that helps a bit!
