### ISSUE TITLE
Extract Data from Pincache

### ISSUE THREAD

**Issue by thiagoramos23** [pinterest/PINCache#24]
Hi, I wonder if there is a way, when saving cache in disk, to retrieve the file of the cache and extract data. I'm using Pincache for store offline data, but I usually need to get the data that was not synchronised  to the server for some reason (probably bugs). 

There is a way to get this file and, perhaps, read in another app?

Sorry to create this issue but i didn't know where to ask.

**Comment by garrettmoon** [comment]
Hey @thiagoramos23, the documentation covers this pretty well. You can get the cache's diskCache and either get the object (which will read from disk and deserialize into an object), or you can get the file path of the object instead with a separate method on PINDiskCache. Hope this helps,

Garrett
