### ISSUE TITLE
PINCache  - (void)trimToDate:(NSDate *)date There is something wrong with the logic of this method.

### ISSUE THREAD

**Issue by sunWaterMood** [pinterest/PINCache#255]
There is something wrong with the logic of this method. The time must be set before the setobject method, and the logic is not correct. Clench the source code and find that as long as the trim method is called, all previous caches will be cleared.

**Comment by garrettmoon** [comment]
@sunWaterMood I'm not sure I understand, can you provide more details?

**Comment by sunWaterMood** [comment]
- (void)trimToDate:(NSDate *)date  Can you tell me how to clear the previous cache?

**Comment by garrettmoon** [comment]
@sunWaterMood I'm sorry, I still don't know what the issue is. If you're simply trying to clear the cache, you can call `removeAllObjects`

If you can provide more details I'm happy to reopen this issue!
