### ISSUE TITLE
Provide prebuilt frameworks for Carthage

### ISSUE THREAD

**Issue by dcaunt** [pinterest/PINCache#26]
Carthage can download prebuilt frameworks if they are attached to a GitHub release.

For example, to prebuild the zip required for 2.0.1:

```
git checkout 2.0.1
carthage build --no-skip-current
carthage archive PINCache
```

Attach the resulting `PINCache.framework.zip` to the release.

**Comment by garrettmoon** [comment]
The idea would be to checkout master

```
carthage build --no-skip-current
carthage archive PINCache
```
then commit the changes and tag that as a release?

**Comment by dcaunt** [comment]
Carthage is smart enough to look at GitHub releases (tags) for the resolved version. So if PINRemoteImage is added to a Cartfile at version 2.0.1, Carthage will look for a GitHub release for that tag. 

The existing 2.0.0 and 2.0.1 releases are fine as is, they would just need a PINCache.framework.zip attaching. 

You want the prebuilt framework to be the same as if it was built from the tag, so it's necessary to check out the tag. Obviously if you are creating the prebuilt framework for Carthage immediately after tagging, master and the latest release tag point to the same commit.

**Comment by garrettmoon** [comment]
Gave it a go, mind testing it worked for 2.0.1?

**Comment by dcaunt** [comment]
Works perfectly, thanks again!
