### ISSUE TITLE
Code clarification on lock/unlock methods of PINDiskCache

### ISSUE THREAD

**Issue by malcommac** [pinterest/PINCache#27]
Hi,
I'm looking at the code and I'm a bit confused.
Just for example, looking at ```setObject:forKey:block``` in ```PINDiskCache.m``` I can see:

```objective-c
...
dispatch_async(_asyncQueue, ^{
        PINDiskCache *strongSelf = weakSelf;
        NSURL *fileURL = nil;
        [strongSelf setObject:object forKey:key fileURL:&fileURL];
        
        if (block) {
            [strongSelf lock];
                block(strongSelf, key, object, fileURL);
            [strongSelf unlock];
        }
    });
```

Why ```strongSelf lock/unlock``` is needed between the return callback call?
No access to files is performed (and in fact inside the ```setObject:forKey:fileURL:``` another lock is made).
Is there any reason I can't understand for this?
It's the same for reading (get) method; is there need to lock a read operation?
Thank you :)

**Comment by garrettmoon** [comment]
It's guaranteed in the api that it's safe to access things like diskByteCount in the callback. It might be a contract that should be changed for perf reasons. I'd be up for someone investigating that change :)
