### ISSUE TITLE
Swift Package Manager compatibility 

### ISSUE THREAD

**Issue by coulonb** [pinterest/PINCache#271]
Hi, 

Do you have any ideas when it will be possible to install with SPM ? 
Thank you,

**Comment by coulonb** [comment]
Any ideas ?

**Comment by sjmueller** [comment]
Since https://github.com/pinterest/PINOperation has SPM support, it'd be great to also have it here for those of us coming from Snapchat's SnapKit!

**Comment by 3a4oT** [comment]
#283

**Comment by garrettmoon** [comment]
Merged! Thank you @3a4oT !
