### ISSUE TITLE
Error in xcode12 compilation

### ISSUE THREAD

**Issue by zhouxubin** [pinterest/PINCache#284]
When I upgraded to xcode12, the compiler reported 23 errors in the morning

`Incompatible block pointer types initializing '__strong PINCacheObjectBlock' (aka 'void (^__strong)(id<PINCaching>  _Nonnull __strong, NSString * _Nonnull __strong, id  _Nullable __strong)') with an expression of type 'PINDiskCacheObjectBlock  _Nullable __strong' (aka 'void (^__strong)(PINDiskCache * _Nonnull __strong, NSString * _Nonnull __strong, id<NSCoding>  _Nullable __strong)')`

**Comment by Mammadbayli** [comment]
I also have the same problem, downgraded to 11.7 for now.

**Comment by abuzzworld** [comment]
emmmmm

**Comment by Plnda** [comment]
https://github.com/pinterest/PINCache/pull/281 this PR will fix it

**Comment by garrettmoon** [comment]
@zhouxubin can you confirm you are using 3.0.1?

**Comment by unamed000** [comment]
I'm having the exact problem

**Comment by garrettmoon** [comment]
@unamed000 what version of PINCache are you using?

**Comment by unamed000** [comment]
@garrettmoon 
I'm using version 3.0.1

**Comment by theoneit** [comment]
was it fixed? any update?

**Comment by garrettmoon** [comment]
@unamed000 3.0.1 was released, please update!
