### ISSUE TITLE
pincache framework problem with Xcode12.3 version

### ISSUE THREAD

**Issue by DhagatKinjal** [pinterest/PINCache#304]
Incompatible block pointer types sending 'void (^)(PINCache * _Nonnull __strong, NSString * _Nonnull __strong, id  _Nullable __strong)' to parameter of type 'PINCacheObjectBlock _Nullable' (aka 'void (^)(id<PINCaching>  _Nonnull __strong, NSString * _Nonnull __strong, id  _Nullable __strong)')

**Comment by garrettmoon** [comment]
@DhagatKinjal are you on the latest version? Can you please upload a sample project?

**Comment by dgcoffman** [comment]
@garrettmoon https://github.com/pinterest/PodToBUILD `make build-test` repros.

**Comment by garrettmoon** [comment]
@dgcoffman that doesn't look to be using the latest version of PINCache.

**Comment by dgcoffman** [comment]
That's correct. I was getting this error in PodToBUILD and resolved by upgrading to PINCache 3.0.3.

**Comment by DhagatKinjal** [comment]
Thank you for your timely response. I will check it out.

**Comment by garrettmoon** [comment]
Glad upgrading fixed it!

**Comment by kinjal-concetto** [comment]
> That's correct. I was getting this error in PodToBUILD and resolved by upgrading to PINCache 3.0.3.

Thanks 👍
