### ISSUE TITLE
Ability to purge expired items

### ISSUE THREAD

**Issue by kerrmarin** [pinterest/PINCache#31]
Hi there,

It would be great to be able to purge items that have expired from the cache. For example, I have a service that returns images with a cache-control header. I would like to have the ability to, when inserting into the cache, specify a date to mark them as expired and then have the ability to remove only the expired items from the cache.

Thanks

**Comment by garrettmoon** [comment]
Would be happy to accept a pull request that implemented this without a performance cost for use that didn't require this functionality.

**Comment by ryanbrodie** [comment]
I second this, purging at the object level rather than the entire cache would be useful in many use cases.

**Comment by garrettmoon** [comment]
@kerrmarin TTL has been implemented as an option. Does this address this issue?
