### ISSUE TITLE
*forKey: and *forKey:block: methods should check object dates against _ageLimit

### ISSUE THREAD

**Issue by benasher44** [pinterest/PINCache#32]
Hello! In a perfect world, setting ```ageLimit``` schedules regular trims of the cache, and the the cache is always free of objects that have expired. In reality, you could set an ```ageLimit``` to 5 minutes, add an object to the cache 2.5 minutes later, and then this object will get to live on for 7.5 minutes instead of the 5 minutes maximum set by setting the ```ageLimit``` (because it missed the cache trim at the 5 minute mark, and it won't get cleared again until the 10 minute mark).

To avoid this scenario entirely, methods like ```objectForKey:``` and ```objectForKey:block:``` should only return objects in the cache if they're actually meant to still be in the cache (i.e. return nil if the object has technically expired but hasn't been cleared yet). Another benefit, aside from avoiding the scenario I mentioned earlier, is that this allows the user to reliably write code like this:

```
[self.someCache objectForKey:myObjectKey block:^(PINDiskCache *cache, NSString *key, id <NSCoding> __nullable object, NSURL * __nullable fileURL) {
    if (object) {
        // use the object
    } else {
        // create/fetch a new one of these objects
    }
}];
```

Without this, you first have to get the ```fileURL```, check the ```fileURL``` file's modification time and compare it against the ```ageLimit```, if that all checks out, then call ```objectForKey:block:```. The issue here though is that if you do the ```fileURL``` file modification time checking asynchronously to avoid holding any locks in PINCache, the following ```objectForKey:block:``` call is not guaranteed to return your object as a ```trimToAgeLimitRecursively``` may have been called during that time and cleared your object!

Does this make sense? Thoughts?

**Comment by garrettmoon** [comment]
Hmm, this is an interesting use of the cache. I don't think the current design of PINCache is catered to the idea that the cache *must* enforce TTL. I think it's catered to the other use case where you generally want to clear out old items so they don't take up too much memory, not because you want to make sure you 'create/fetch' new objects.

If you feel strongly about adding the feature, I'd be open to a pull request that allowed the feature to optionally be enabled and that didn't cause a hit to performance when not enabled.

**Comment by benasher44** [comment]
I'd be happy to submit a PR! In terms of supporting this feature, would setting the ageLimit to a value > 0 be enough to consider this feature enabled? Given the description of ageLimit in PINDiskCache.h ("```The maximum number of seconds an object is allowed to exist in the cache…```" specifically), I don't think this new behavior would be a surprising result to any existing users of PINCache.

**Comment by garrettmoon** [comment]
@benasher44 it may not be surprising, based on the documentation, but there may be a performance hit for some users? I guess it depends on the performance implications. If they are small and if cache misses aren't going to be greatly increased, I'm ok with ageLimit > 0 enabling the feature. If not, I'd be worried about this especially with no way to turn off the feature.

**Comment by benasher44** [comment]
Done here: #63

**Comment by garrettmoon** [comment]
Whoo!
