### ISSUE TITLE
Cocoapods, support watchOS platform

### ISSUE THREAD

**Issue by cyril94440** [pinterest/PINCache#35]
Would be great if you could add watchOS platform support

**Comment by garrettmoon** [comment]
Would happily accept a pull request! FYI, sharing a disk cache between an extension and an app is currently unsupported and would require quite a bit of work to allow.

**Comment by cyril94440** [comment]
I am just talking about caching on the extension so on the watch. Not cache syncing.
I guess it's just about removing UIApp notifications, but not sure about how it is used in PINCache

**Comment by garrettmoon** [comment]
@cyril94440 PINCache already supports that, have a look at PIN_APP_EXTENSIONS
