### ISSUE TITLE
Use NS_EXTENSION_UNAVAILABLE_IOS instead of PIN_APP_EXTENSIONS

### ISSUE THREAD

**Issue by jparise** [pinterest/PINCache#37]
`NS_EXTENSION_UNAVAILABLE_IOS` can be used to mark symbols as unavailable to extensions. This should allow us to remove the `PIN_APP_EXTENSIONS` define and produce one library for both application and extensions.

Inspired by AFNetworking/AFNetworking#2737.

**Comment by garrettmoon** [comment]
From my understanding, this will only allow us to mark methods as unavailable for use in extensions, it *won't* allow us to compile separate code paths. So I'm not sure it will actually add value? :(

**Comment by garrettmoon** [comment]
Going to close this for now for the same reason as per [here](https://github.com/pinterest/PINRemoteImage/issues/93)
