### ISSUE TITLE
Request: non hard-coded name consts

### ISSUE THREAD

**Issue by soundspectrum** [pinterest/PINCache#39]
Hi!

First, many things for making your work open!

In PINDiskCache.m, this is a kind request to make the values for `PINDiskCachePrefix` and `PINDiskCacheSharedName` changeable at build time (i.e. not hard-coded into the repository!).  

Suggestions that would all work:
  * check a if a macro is defined and use that instead if defined
  * add a NSString param to initWithName:rootPath that is used instead of PINDiskCachePrefix if non-nil
  * put a macro in PINCache.h that is used as a name base (and is skipped if is already defined)

Thanks!!
Drew

**Comment by garrettmoon** [comment]
Hey Drew, we're open to pull requests, sounds like you already know how you might implement it!
