### ISSUE TITLE
OS_OBJECT_USE_OBJC not set

### ISSUE THREAD

**Issue by tapz** [pinterest/PINCache#4]
Code crashes here. Why is that? The deployment target is 8.0 so it should use ARC.

- (void)dealloc
{
    [[NSNotificationCenter defaultCenter] removeObserver:self];

    #if !OS_OBJECT_USE_OBJC
    dispatch_release(_queue);  <-----------------CRASH
    dispatch_release(_lockSemaphore);
    _queue = nil;
    #endif
}

**Comment by garrettmoon** [comment]
I assume you using CocoaPods? If so, you'll want to take a look here: http://guides.cocoapods.org/syntax/podspec.html#deployment_target

Anyway, this isn't an issue specific to PINCache, OS_OBJECT_USE_OBJC is defined by the SDK. Try command clicking on it or looking in object.h

**Comment by tapz** [comment]
Should this in PINCache.podspec be 6.0 in order to use ARC?

s.ios.deployment_target = '5.0'

**Comment by garrettmoon** [comment]
Ah! You're using an old version, please update to the latest commit and your issue should be resolved.

**Comment by tapz** [comment]
I updated my pods today. If the pod is old, please update it.

**Comment by tapz** [comment]
When I go to https://github.com/pinterest/PINCache and lick PINCache.podfile it has target version 5.0. How do I access the latest commit?

**Comment by garrettmoon** [comment]
Deployment spec should be 5.0, we wrote the code to support it. The fix is in PINCache.m. There is no _queue iVar anymore, it's been renamed _concurrentQueue.

You can specify a commit in CocoaPods like so:

	pod 'PINCache', :git => 'https://github.com/pinterest/PINCache.git', :commit => 'b9d152954e56d18b196b180188752040e9ac6cf9'

I'll probably do a 2.0.1 release soon so that you don't have to specify the commit hash.
