### ISSUE TITLE
CocoaPods 2.1.2 Update with PINDiskCache bugfix

### ISSUE THREAD

**Issue by mRs-** [pinterest/PINCache#43]
The current version (2.1.1) is not used for production at the moment. Maybe a new podspec should created for cocoapods as soon as possible to fix this issues with all new installation of **PINRemoteImage** and **PINCache**.

**Comment by garrettmoon** [comment]
Updated PINCache, it's unnecessary to update PINRemoteImage, it will pick this up as it only requires >= 2.1
