### ISSUE TITLE
Crash on dealloc

### ISSUE THREAD

**Issue by Kosikowski** [pinterest/PINCache#5]
Hi,  I've created simple project to test PINCache, and the app crashed on dealloc method in either PINMemoryCache or PINDiskCache. Steps to reproduce:
1. Create simple IOS.8.3 project with PINCache added using cocoapods
2. Add one the following line in the e.g viewDidLoaded in main view controller
[[PINMemoryCache alloc]init]; //crash
[[PINCache alloc]initWithName:@"Name"]l; //crash

I was able to establish that re-adding files to Pod-PINCache project fixes the problem, but in my opinion that's not proper fix for it. Probably user wouldn't like the idea of updating project file when updating pods.
Thanks.

**Comment by garrettmoon** [comment]
This has been fixed, however we haven't pushed out a new version. To get the fix, you can specify the latest commit with:

pod 'PINCache', :git => 'https://github.com/pinterest/PINCache.git', :commit => 'b9d152954e56d18b196b180188752040e9ac6cf9'

We'll release a 2.0.1 soon.

**Comment by Kosikowski** [comment]
Thank you!
