### ISSUE TITLE
Long keys don't work for disk cache due to filename length limit

### ISSUE THREAD

**Issue by shwu** [pinterest/PINCache#50]
The symptom we are seeing is that keys above a certain length cause the cache to either not save or miss when accessed.  After a quick empirical experiment it seems like the maximum key length is 255 characters (UNIX filename limit) and since special characters are escaped, their presence lowers the maximum limit.

We're using URLs as keys, some of which can be very long.

**Comment by garrettmoon** [comment]
Hi @shwu, can you be a bit more specific? Is this specifically the disk cache?

**Comment by erichoracek** [comment]
I've encountered this issue as well when caching Mapbox static map images with very long URLs. Applying a SHA1 to the key solved the issue for me. However, it would probably make more sense to fix this at the framework level.

**Comment by shwu** [comment]
@garrettmoon Yep, this is specifically the disk cache.  When trying to write to disk with a long key (over 255 characters after escaping) the object will not be saved.  Our workaround was to hash the URL, as @erichoracek suggested, but again it seems like a framework-level fix is appropriate in this case.

**Comment by shwu** [comment]
Awesome!
