### ISSUE TITLE
NSKeyedArchiver adds extra bytes to the stored file causing issues on different media types

### ISSUE THREAD

**Issue by ItamarM** [pinterest/PINCache#58]
While the Disk Cache storing mechanism is great for image and text files, it causing some issues with other media types such as videos (The AVPlayer cannot handle that file type).

**Comment by garrettmoon** [comment]
Do those media types support the NSCoding protocol correctly? All items stored in PINCache need to support NSCoding.

**Comment by ItamarM** [comment]
NSData is supporting NSCoding, but when you persist it with KeyArchiver it adds meta data.

**Comment by garrettmoon** [comment]
@ItamarM and that meta data isn't removed when it's restored? Can you provide an example file where encoding and decoding from NSData mutates the NSData? This sounds like more of an underlying issue with NSCoding and not an issue with PINCache.

The only way I can see working around this is to allow for PINDiskCache to either have a decode / encode delegate or make for easy subclassing to override the existing encode / decode.

**Comment by garrettmoon** [comment]
I'm going to close this, lemme know if you can provide further information.

**Comment by thekirankumar** [comment]
For people using PINCache along with VideoNode or AVPlayer, you can use a custom serializer to just pass through the NSData as is without archiving. This worked for us.
Also additionally you need to have a custom key encoder to make the filenames on disk to end with .mp4
