### ISSUE TITLE
Unable to specify memory cache cost when adding object to PINCache

### ISSUE THREAD

**Issue by timonus** [pinterest/PINCache#64]
When adding objects to `PINCache` via `-setObject:forKey:` those objects are internally stored to a `PINMemoryCache` and `PINDiskCache`. Trouble is, the value specified for the object stored in the `PINMemoryCache` is zero, meaning that trimming the memory cache by setting a cost limit doesn't work. It would be handy if there was some way to specify cost either explicitly when calling `-setObject:forKey:` on the outer `PINCache` or by having the objects passed in conform to a protocol indicating their cost, something like a `PINMemoryCacheCost` protocol.

**Comment by garrettmoon** [comment]
I like the former idea as that's how it works for the memoryCache and implementing a protocol seems like a bit more work on the API user.

**Comment by joshbernfeld** [comment]
I agree, as of right now I need to manually modify the source to get the intended functionality

**Comment by garrettmoon** [comment]
@joshbernfeld would happily accept a pull request!

**Comment by garrettmoon** [comment]
Hey! This got fixed!

**Comment by timonus** [comment]
In the fullness of time!
