### ISSUE TITLE
setObject not working

### ISSUE THREAD

**Issue by cyril94440** [pinterest/PINCache#7]
Hi,

I am not able to save an object.

The log shows : PINDiskCache.m (303) ERROR: The operation couldn’t be completed. (Cocoa error 4.)

**Comment by garrettmoon** [comment]
@cyril94440 that's an error reported by the system when writing the object to disk. Can you give more information? A small sample program showing the issue? What version of PINCache are you using, or even better, what is the last commit?

**Comment by cyril94440** [comment]
Hi,
I'll try to provide more information but for now, I didn't change anything in my code directly linked to PINCache. I am using the last version using cocoa pods

**Comment by cyril94440** [comment]
I am using the Parse-NSCoding repo.
Can it be due to a bad NSCoding implementation ?

**Comment by garrettmoon** [comment]
@cyril94440 The error is an error occurring when setting the file modification date. It's returned by the system.

If I were debugging this, I'd put a breakpoint at the top of setFileModificationDate in PINDiskCache and see what is getting passed into setAttributes. If it's not immediately obvious what the issue is, can you paste what date and fileURL are in the case where it errors?

**Comment by cyril94440** [comment]
Nothing strange :/

2015-07-16 16:25:21 +0000

file:///var/mobile/Containers/Data/Application/5189A230-65E2-4DDD-927F-27817C3711AA/Library/Caches/com.pinterest.PINDiskCache.PINCacheShared/alreadyMatchUsers

**Comment by garrettmoon** [comment]
Hmm, are you using the cache from an extension or watch extension? Do you have multiple cache's with the same name?

**Comment by cyril94440** [comment]
I am using group for sharing files with the watch extension. 
However I am not even using an apple watch. So the code is running only for the iOS app part. 
I am using the sharedCache only.
Maybe there is something happening with the group files...?

**Comment by garrettmoon** [comment]
@cyril94440 PINCache does not yet support running in multiple processes at once (i.e. phone app and watch app) yet see https://github.com/pinterest/PINCache/issues/2

It could indeed be the OS 'protecting' access to group files. I'm not sure :(

I'd happily accept a pull request to implement the feature requested in the above github issue.
