### ISSUE TITLE
costLimit not preventing very large in memory cache size

### ISSUE THREAD

**Issue by dmauro** [pinterest/PINCache#77]
We're using PINRemoteImage and asking it to download several very large images (~5k x 4k). When it does this memory spikes up to 1GB and the app gets killed by the system. This seems to be the case even if we set our costLimit to something far below 1GB:

```
    var imagePrefetcher: PINRemoteImageManager = {
        let manager = PINRemoteImageManager.sharedImageManager()
        manager.cache.diskCache.byteLimit = 20_000_000
        manager.cache.memoryCache.costLimit = 300_000_000
        return manager
    }()
```

It seems like perhaps the costLimit is simply not being honored? Or is it possible these are ending up in memory somewhere else first?

We're making the download calls serially all on the main thread:
```
        for image in imagesToCache {
            imagePrefetcher.downloadImageWithURL(image) { result in
```

**Comment by garrettmoon** [comment]
@dmauro currently has a bug, PINRemoteImage doesn't represent the cost in bytes but instead the cost in pixels :( I'm working on a big refactor which has this fixed, but it might be a while until it makes it in. Would happily accept a pull request to address it in the meantime!

**Comment by dmauro** [comment]
Bummer. Well, we'll work around this bug for now. Thanks for the heads up that it might be a little while.

**Comment by garrettmoon** [comment]
This should be fixed in the PINRemoteImage beta!
