### ISSUE TITLE
checking if image is cached

### ISSUE THREAD

**Issue by DanielRanLehmann** [pinterest/PINCache#79]
I might be missing something obvious. I'm using PINcache to store my images that is async plugged into a custom cell in a collectionView.

How can I check if an image is cached?

Is there any similar method to SDWebImage where you can check if an image is cached on disk like this:
- (BOOL)diskImageExistsForURL:(NSURL *)url;

- Daniel Lehmann

**Comment by garrettmoon** [comment]
@DanielRanLehmann You can obviously just call objectForKey, but that will instantiate the object off disk which if you just want to check if it's available is expensive. Instead, you can access the memoryCache and diskCache directly. objectForKey on the memory cache will determine existence (and isn't expensive). fileURLForKey is the cheapest way to check existence on the disk cache.

I'd be happy to accept a pull request which exposes methods on the memoryCache, diskCache and PINCache to essentially do this all.

**Comment by DanielRanLehmann** [comment]
Thanks for the quick response :+1: I will look into it right away and make a pull request if it works out..

**Comment by danielgalasko** [comment]
@garrettmoon I think this can be closed:)

**Comment by garrettmoon** [comment]
Thanks!
