### ISSUE TITLE
Problem with swift

### ISSUE THREAD

**Issue by klevison** [pinterest/PINCache#8]
http://stackoverflow.com/questions/31468121/pincache-objectforkey-returning-nscoding-and-cant-casting-it

So, using objC it is perfect, but when I wanna cast with swift I had EXC_BAD_ACCESS

When I call `objectForKey`

`- (id <NSCoding>)objectForKey:(NSString *)key;`

And I have nothing cached for that key, but Swift understand that the object is an NSConding. So, if I have values into a key, I have no problems.

So, how can I cast this NSCoding result and compare with nil value. I only need to know if the object return from PINCache is nil (never cached).

I've already tried:

```swift
private func setupTrucks() {
    let trucksCached: AnyObject? = PINDiskCache.sharedCache().objectForKey(TruckCache.key)
    if let _truck = trucksCached as? [Truck] { //EXC_BAD_ACCESS here
        print(_truck)
    }
}

private func setupTrucks() {
    let trucksCached = PINDiskCache.sharedCache().objectForKey(TruckCache.key) as [Truck] //EXC_BAD_ACCESS here
    if trucksCached.count > 0 {
        print(_truck)
    }
}
```

**Comment by rcancro** [comment]
Hey,

It looks like the return type of the synchronous `objectForKey:` methods needs to be marked as `__nullable`. Otherwise Swift doesn't know the return type can be optional.

I just submitted a PR to fix this:
https://github.com/pinterest/PINCache/pull/9

(and it looks like it has already been merged!!)

**Comment by klevison** [comment]
Please update `podspec`file

**Comment by garrettmoon** [comment]
We probably won't be updating the podspec for this, however you can specify a commit with cocoa pods:

`pod 'PINCache', :git => 'https://github.com/pinterest/PINCache.git', :commit => 'd68c82fbcf6300e6a968c7fd3be0092f5ab42786'

**Comment by klevison** [comment]
OK. Thanks :)
