### ISSUE TITLE
Provide prebuilt framework for tvOS

### ISSUE THREAD

**Issue by ittna** [pinterest/PINCache#89]
Release only contains iOS and Mac framework at the moment. Could you add tvOS as well?

**Comment by ittna** [comment]
pull request #90 adds tvOS target to project file which should create tvOS version of the framework

**Comment by garrettmoon** [comment]
Awesome! I totally missed the pull request, I'll try and look at it this week. Thank you @ittna!

**Comment by garrettmoon** [comment]
Sorry about not getting this merged in sooner, it's in now!
