### ISSUE TITLE
Podfile - containsObjectForKey support

### ISSUE THREAD

**Issue by jaredsson** [pinterest/PINCache#91]
Because the latest release is from before `containsObjectForKey` was added, I am not able to use that API, do you mind adding a new release for it or showing me how to access it?

I am using Swift with the use frameworks Cocoapods option.

from my Podfile:

pod 'PINCache', :git => 'https://github.com/pinterest/PINCache.git'

Thanks btw, I find this cache very useful!

**Comment by garrettmoon** [comment]
@jaredsson if you'd like to use that API before it's released, you can specify a commit in your podfile

```
pod 'PINCache', :git => 'https://github.com/pinterest/PINCache.git', :commit => '6987736c99d8829b2f3f3200f3d1d7e0984baa2b'
```
