### ISSUE TITLE
PINMemoryCache doesn't appear to update its totalCost when an object is replaced

### ISSUE THREAD

**Issue by davehakim** [pinterest/PINCache#92]
If a caller calls 

```
- (void)setObject:(id)object forKey:(NSString *)key withCost:(NSUInteger)cost
```

on a PINMemoryCache for an existing key, the cost associated with the currently stored object is never deducted from the the cache's `totalCost` 

It seems like it might even make sense to call

```
    [self removeObjectAndExecuteBlocksForKey:key];
```

At the beginning of the setObject:forKey:withCost method if the key already exists

**Comment by garrettmoon** [comment]
@davehakim Yeesh, that's bad! Would you be willing to add a unit test to demonstrate this?

**Comment by davehakim** [comment]
Sure thing

**Comment by davehakim** [comment]
Sent up PR https://github.com/pinterest/PINCache/pull/93 with a unit test and a fix that just targets the totalCost issue. I didn't do a full call to `removeObjectAndExecuteBlocksForKey` since I wasn't sure if having the willRemove/didRemove object blocks was desired but could certainly update the PR if it is.

**Comment by garrettmoon** [comment]
Merged, thank you!

**Comment by garrettmoon** [comment]
Can you open a separate issue for the willRemove/didRemove? That way it can be discussed in a thread of its own?

**Comment by davehakim** [comment]
Sure thing! Thx
