### ISSUE TITLE
Advantages of PINCache over NSURLCache?

### ISSUE THREAD

**Issue by danielgalasko** [pinterest/PINCache#95]
I had a discussion with a colleague the other day who was advocating we use `NSURLCache` over `PINCache`. I was asked: what does `PINCache` offer that `NSURLCache` doesn't offer? I was rather at a loss.

As someone who hasn't used `NSURLCache` I don't know much about it but "NSURLCache provides a composite in-memory and on-disk caching mechanism for URL requests to your application"[link](http://nshipster.com/nsurlcache/). This seems to be pretty much what PINCache is doing too.

One thing I thought of is that `PINCache` prunes objects by LRU which is maybe something `NSURLCache` doesn't? But I am skeptical.

Would love to hear comments on this so I can help get a better understanding to advocate `PINCache` over the ones provided by Foundation...

**Comment by danielgalasko** [comment]
I also understand that `NSURLCache` explicitly caches `NSURLResponse's` but I am curious as to what the creators/community think the advantages are:)

**Comment by maicki** [comment]
@danielgalasko NSURLCache is build explicitly for caching URL requests. PINCache can be used for caching way more things than just URL requests. That said I guess you have to write a layer on top of PINCache to get full functionality parity with NSURLCache.

As you already said you don't have any insights into NSURLCache. You don't know which strategy in terms of caching Apple uses internally. PINCache is open source. If you wanna know how some specifics are working, just look it up and read the code :)

**Comment by danielgalasko** [comment]
@maicki thanks for the response! the transparency of PINCache is a definite advantage but the truth of the matter is that employing Apple frameworks have a slightly easier convince rate than any OSS project. Especially since these projects need to be maintained for free:)

I just don't think having a framework be more 'open' is necessarily the strongest advantage for use but it is an advantage.

I guess what it comes down to is that `PINCache` is more a 'superior' replacement for `NSCache` in that it comes with LRU purging, memory warning handling, and support for concurrent disk and memory caching. When it comes to caching network stuff `NSURLCache` might be a better goto?

Maybe a better way to phrase it would be: What are the disadvantages to using `NSURLCache` for network response caching (majority of modern use cases)? Since we can typically rely on Apple maintaining frameworks more than anyone else. ¯\_(ツ)_/¯

**Comment by garrettmoon** [comment]
@danielgalasko Having worked at Apple and on NSCache (ok, I worked on one bug), I would suggest that a platform owned project is not inherently maintained better :)

To answer your question, beyond transparency, I haven't investigated if NSURLCache is better for network response caching compared to PINCache. If all you're doing is caching the actual response of an NSURLConnection / Session it may likely be a better option. But if you're doing any type of processing of the responses from NSURLConnection, something like PINCache is likely better. For example, PINRemoteImage uses PINCache so that it can process the responses into decompressed UIImages. Re-decompressing them on every request would be expensive.

**Comment by garrettmoon** [comment]
I'm going to close this issue to clean things up, but I'm happy to continue discussing :)

**Comment by danielgalasko** [comment]
Ah yes! @garrettmoon thanks, thats actually something I brought up a little earlier. `NSURLCache` is probably best used for JSON responses and for more complex tastes it seems like `PINCache` is the way to go. Having been to the labs at DubDub I can admit that the code Apple writes isn't always up to the 'best standards'. And OS libraries have the advantage of not being constrained by iOS version updates.

Regarding maintenance, all I meant was that in Apples case they rarely throw away public API without offering some kind of alternative. Thats not to say their stuff doesn't have bugs. When it comes to OS if a maintainer steps down then thats where things get interesting. One of the reasons why I always prefer using libraries built by fairly large organisations with a large user base and a reasonable investment in the software produced.

Was just keen to hear your thoughts on the advantages. Especially since a lot of the bigger companies tend to reinvent the wheel because they have the manpower:)

Regardless I still love this library alongside `PINRemoteImage`. Just wanted some ammo for internal discussion regarding the benefits 👍
